### ISSUE TITLE
Enum Handling in DTO

### ISSUE THREAD

**Issue by dwcahyo23** [Brakebein/prisma-generator-nestjs-dto#46]
```
enum Status {
    Y
    N
    C
}

  /// @description WO VERIFY
  /// @IsNotEmpty()
  repClosed   Status @default(value: N)
```

Enum hidden in createDto / updateDto in v1.23.1

**Comment by Brakebein** [comment]
It's hidden because it has a default value. You need to add the `/// @DtoCreateOptional` and `/// @DtoUpdateOptional` annotations to include it in the CreateDto and UpdateDto (should be independent of the type).

See last point of the conditions when a field is omitted: [Readme - CreateDto](https://github.com/Brakebein/prisma-generator-nestjs-dto?tab=readme-ov-file#createdto)
