### ISSUE TITLE
Suggestion: Collaboration with "Prisma-Utils"

### ISSUE THREAD

**Issue by ChristopherCapito** [Brakebein/prisma-generator-nestjs-dto#5]
Hello

first of all, many thanks for the great work you did here. This is the best DTO generator for Prisma and NestJS I came across so far.

May I suggest you collaborate or merge with the "Prisma-Utils" project? The project includes service generators, but has issues with DTO generation and Swagger. All those issues are solved with your library.

I have used the two in conjunction to create a full service layer with precise DTOs. Using the two in conjunction speeds up development quite a bit. Using the two in conjunction allowed for a clean separation between pure business logic and data access, making implementation of business logic much faster.

Sidenote: I already told the guy over at prisma-utils about your DTO generator, as the prisma-utils implementation is lacking in some regards.

This is the project. It includes other utils aswell.
https://github.com/prisma-utils/prisma-utils

**Comment by Brakebein** [comment]
Thanks for the suggestion. I had a (short) look at his implementation: it seems to be very different, not only the implementation itself, but also the generated output. Additionally, there are different annotations. Considering this, it seems hard to merge both projects without losing backward-compatibility. I understand that it would be nice to have everything under one single namespace, especially since `@prisma-utils` sounds kind of official. But I guess the task to agree on a common basis and to merge these different code bases would be quite cumbersome and time-consuming.

**Comment by ChristopherCapito** [comment]
You are right. The other author also is striving for a strictly restful implementation, so there is no use for the create/connect DTOs in your lib, which i really like.
